<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schema"
    nsURI="http://org.lh.dmlj.schema/schema.ecore" nsPrefix="org.lh.dmlj.schema">
  <eClassifiers xsi:type="ecore:EEnum" name="AreaProcedureCallFunction">
    <eLiterals name="EVERY_DML_FUNCTION" value="-1"/>
    <eLiterals name="READY_EXCLUSIVE"/>
    <eLiterals name="READY_EXCLUSIVE_UPDATE" value="1"/>
    <eLiterals name="READY_EXCLUSIVE_RETRIEVAL" value="2"/>
    <eLiterals name="READY_PROTECTED" value="3"/>
    <eLiterals name="READY_PROTECTED_UPDATE" value="4"/>
    <eLiterals name="READY_PROTECTED_RETRIEVAL" value="5"/>
    <eLiterals name="READY_SHARED" value="6"/>
    <eLiterals name="READY_SHARED_UPDATE" value="7"/>
    <eLiterals name="READY_SHARED_RETRIEVAL" value="8"/>
    <eLiterals name="READY_UPDATE" value="9"/>
    <eLiterals name="READY_RETRIEVAL" value="10"/>
    <eLiterals name="FINISH" value="11"/>
    <eLiterals name="COMMIT" value="12"/>
    <eLiterals name="ROLLBACK" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AreaProcedureCallSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callTime" eType="#//ProcedureCallTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//AreaProcedureCallFunction"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" lowerBound="1"
        eType="#//Procedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AreaSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicSubareaName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" eType="#//SchemaArea"
        eOpposite="#//SchemaArea/areaSpecifications"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offsetExpression" eType="#//OffsetExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//SchemaRecord" eOpposite="#//SchemaRecord/areaSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemOwner" lowerBound="1"
        eType="#//SystemOwner" eOpposite="#//SystemOwner/areaSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuplicatesOption">
    <eLiterals name="FIRST"/>
    <eLiterals name="LAST" value="1"/>
    <eLiterals name="BY_DBKEY" value="2"/>
    <eLiterals name="NOT_ALLOWED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="picture" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" eType="#//Usage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Element" eOpposite="#//Element/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyElements" upperBound="-1"
        eType="#//KeyElement" eOpposite="#//KeyElement/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occursSpecification" eType="#//OccursSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Element"
        eOpposite="#//Element/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" eType="#//SchemaRecord"
        eOpposite="#//SchemaRecord/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefines" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexedSetModeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displacementPageCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicIndexName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compressed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duplicatesOption" eType="#//DuplicatesOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="naturalSequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//KeyElement" containment="true" eOpposite="#//KeyElement/key"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberRole" eType="#//MemberRole"
        eOpposite="#//MemberRole/sortKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" eType="#//SchemaRecord"
        eOpposite="#//SchemaRecord/keys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbkey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortSequence" eType="#//SortSequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//Element" eOpposite="#//Element/keyElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Key"
        eOpposite="#//Key/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LocationMode">
    <eLiterals name="CALC" literal="CALC"/>
    <eLiterals name="DIRECT" value="1"/>
    <eLiterals name="VIA" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberRole" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="membershipOption" eType="#//SetMembershipOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priorDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//SchemaRecord" eOpposite="#//SchemaRecord/memberRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//Set"
        eOpposite="#//Set/members"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortKey" eType="#//Key"
        eOpposite="#//Key/memberRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramTargetAnchor" eType="#//DiagramLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramSourceAnchor" eType="#//DiagramLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramBendpoints" upperBound="-1"
        eType="#//DiagramLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLabelLocation" lowerBound="1"
        eType="#//DiagramLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccursSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependingOn" eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OffsetExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offsetPageCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offsetPercent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnerRole" eSuperTypes="#//Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priorDbkeyPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//SchemaRecord" eOpposite="#//SchemaRecord/ownerRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//Set"
        eOpposite="#//Set/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcedureCallTime">
    <eLiterals name="BEFORE"/>
    <eLiterals name="AFTER" value="1"/>
    <eLiterals name="ON_ERROR_DURING" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordProcedureCallSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callTime" eType="#//ProcedureCallTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//RecordProcedureCallVerb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" lowerBound="1"
        eType="#//Procedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RecordProcedureCallVerb">
    <eLiterals name="EVERY_DML_FUNCTION" value="-1"/>
    <eLiterals name="CONNECT"/>
    <eLiterals name="DISCONNECT" value="1"/>
    <eLiterals name="ERASE" value="2"/>
    <eLiterals name="FIND" value="3"/>
    <eLiterals name="GET" value="4"/>
    <eLiterals name="MODIFY" value="5"/>
    <eLiterals name="STORE" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eOperations name="getArea" eType="#//SchemaArea">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getProcedure" eType="#//Procedure">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRecord" eType="#//SchemaRecord">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRecord" eType="#//SchemaRecord">
      <eParameters name="areaName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="recordId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eOperations>
    <eOperations name="getSet" eType="#//Set">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//SchemaArea" containment="true" eOpposite="#//SchemaArea/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
        eType="#//Procedure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="records" upperBound="-1"
        eType="#//SchemaRecord" containment="true" eOpposite="#//SchemaRecord/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sets" upperBound="-1" eType="#//Set"
        containment="true" eOpposite="#//Set/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramData" lowerBound="1"
        eType="#//DiagramData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaArea">
    <eOperations name="getRecord" eType="#//SchemaRecord">
      <eParameters name="recordId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eOperations>
    <eOperations name="getRecord" eType="#//SchemaRecord">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="areaSpecifications" upperBound="-1"
        eType="#//AreaSpecification" containment="true" eOpposite="#//AreaSpecification/area"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//SystemOwner" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
        eType="#//AreaProcedureCallSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="records" upperBound="-1"
        eType="#//SchemaRecord" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema" eOpposite="#//Schema/areas"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaRecord" eSuperTypes="#//DiagramNode">
    <eOperations name="getElement" eType="#//Element">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRole" eType="#//Role">
      <eParameters name="setName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="-1"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="-1"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragmented" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationMode" eType="#//LocationMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumFragmentLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumRootLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefixLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageMode" eType="#//StorageMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="areaSpecification" eType="#//AreaSpecification"
        eOpposite="#//AreaSpecification/record"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calcKey" eType="#//Key"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true" eOpposite="#//Element/record"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Key"
        containment="true" eOpposite="#//Key/record"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberRoles" upperBound="-1"
        eType="#//MemberRole" derived="true" eOpposite="#//MemberRole/record"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerRoles" upperBound="-1"
        eType="#//OwnerRole" derived="true" eOpposite="#//OwnerRole/record"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
        eType="#//RecordProcedureCallSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElements" lowerBound="1"
        upperBound="-1" eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema" eOpposite="#//Schema/records"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viaSpecification" eType="#//ViaSpecification"
        containment="true" eOpposite="#//ViaSpecification/record"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//SetMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="#//SetOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexedSetModeSpecification"
        eType="#//IndexedSetModeSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        upperBound="-1" eType="#//MemberRole" containment="true" eOpposite="#//MemberRole/set"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//OwnerRole"
        containment="true" eOpposite="#//OwnerRole/set"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema" eOpposite="#//Schema/sets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemOwner" eType="#//SystemOwner"
        containment="true" eOpposite="#//SystemOwner/set"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viaMembers" upperBound="-1"
        eType="#//ViaSpecification" eOpposite="#//ViaSpecification/set"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetMembershipOption">
    <eLiterals name="MANDATORY_AUTOMATIC"/>
    <eLiterals name="MANDATORY_MANUAL" value="1"/>
    <eLiterals name="OPTIONAL_AUTOMATIC" value="2"/>
    <eLiterals name="OPTIONAL_MANUAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetMode">
    <eLiterals name="CHAINED"/>
    <eLiterals name="INDEXED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SetOrder">
    <eLiterals name="FIRST"/>
    <eLiterals name="LAST" value="1"/>
    <eLiterals name="NEXT" value="2"/>
    <eLiterals name="PRIOR" value="3"/>
    <eLiterals name="SORTED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SortSequence">
    <eLiterals name="ASCENDING"/>
    <eLiterals name="DESCENDING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageMode">
    <eLiterals name="FIXED"/>
    <eLiterals name="FIXED_COMPRESSED" value="1"/>
    <eLiterals name="VARIABLE" value="2"/>
    <eLiterals name="VARIABLE_COMPRESSED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemOwner" eSuperTypes="#//DiagramNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="areaSpecification" eType="#//AreaSpecification"
        eOpposite="#//AreaSpecification/systemOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//Set"
        eOpposite="#//Set/systemOwner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViaSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displacementPageCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicDisplacementName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
        eType="#//SchemaRecord" eOpposite="#//SchemaRecord/viaSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//Set"
        eOpposite="#//Set/viaMembers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Usage">
    <eLiterals name="DISPLAY"/>
    <eLiterals name="COMPUTATIONAL" value="1"/>
    <eLiterals name="COMPUTATIONAL_1" value="2"/>
    <eLiterals name="COMPUTATIONAL_2" value="3"/>
    <eLiterals name="COMPUTATIONAL_3" value="4"/>
    <eLiterals name="BIT" value="5"/>
    <eLiterals name="POINTER" value="6"/>
    <eLiterals name="DISPLAY_1" value="7"/>
    <eLiterals name="CONDITION_NAME" value="88"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLocation" lowerBound="1"
        eType="#//DiagramLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eyecatcher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//DiagramLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zoomLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0d"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showGrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
