/**
 * Copyright (C) 2025  Luc Hermans
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If
 * not, see <http://www.gnu.org/licenses/>.
 * 
 * Contact information: kozzeluc@gmail.com.
 */
package org.lh.dmlj.schema.editor.wizard._import.schema;

import static org.lh.dmlj.schema.editor.extension.ExtensionPointConstants.ELEMENT_IMPORT_TOOL;
import static org.lh.dmlj.schema.editor.extension.ExtensionPointConstants.ELEMENT_IMPORT_TOOLS;
import static org.lh.dmlj.schema.editor.extension.ExtensionPointConstants.ELEMENT_LAYOUT_MANAGER;
import static org.lh.dmlj.schema.editor.extension.ExtensionPointConstants.ELEMENT_LAYOUT_MANAGERS;
import static org.lh.dmlj.schema.editor.extension.ExtensionPointConstants.EXTENSION_POINT_IMPORT_ID;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Properties;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Assert;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.OperationCanceledException;
import org.eclipse.core.runtime.Path;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.jface.operation.IRunnableWithProgress;
import org.eclipse.jface.viewers.IStructuredSelection;
import org.eclipse.jface.viewers.StructuredSelection;
import org.eclipse.jface.wizard.IWizardPage;
import org.eclipse.jface.wizard.Wizard;
import org.eclipse.ui.IImportWizard;
import org.eclipse.ui.IWorkbench;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.part.FileEditorInput;
import org.eclipse.ui.part.ISetSelectionTarget;
import org.lh.dmlj.schema.ConnectionLabel;
import org.lh.dmlj.schema.ConnectionPart;
import org.lh.dmlj.schema.Connector;
import org.lh.dmlj.schema.DiagramLocation;
import org.lh.dmlj.schema.Schema;
import org.lh.dmlj.schema.SchemaFactory;
import org.lh.dmlj.schema.SchemaRecord;
import org.lh.dmlj.schema.Set;
import org.lh.dmlj.schema.editor.Plugin;
import org.lh.dmlj.schema.editor.common.Tools;
import org.lh.dmlj.schema.editor.extension.DataEntryPageExtensionElement;
import org.lh.dmlj.schema.editor.extension.ExtensionElementFactory;
import org.lh.dmlj.schema.editor.extension.ImportToolExtensionElement;
import org.lh.dmlj.schema.editor.extension.LayoutManagerExtensionElement;
import org.lh.dmlj.schema.editor.importtool.AbstractRecordLayoutManager;
import org.lh.dmlj.schema.editor.importtool.IDataEntryContext;
import org.lh.dmlj.schema.editor.importtool.IDataEntryPageController;
import org.lh.dmlj.schema.editor.log.Logger;
import org.lh.dmlj.schema.editor.preference.PreferenceConstants;
import org.lh.dmlj.schema.editor.wizard._import.ImportWizardPage;

/**
 * This wizard is used for both importing (import mode; this is the default operating mode) and updating (update
 * mode) a schema. Setting the operating mode must be done by calling the setUpdateMode PRIOR to calling init(...). 
 */
public class SchemaImportWizard extends Wizard implements IImportWizard {
	private static final Logger logger = Logger.getLogger(Plugin.getDefault());
	
	private ImportToolExtensionElement activeImportToolExtensionElement;	
	private IDataEntryContext context = new DataEntryContext();
	private List<ImportWizardPage> dataEntryWizardPages;
	private File fileToUpdate;
	private List<ImportToolExtensionElement> importToolExtensionElements;
	private ImportToolSelectionPage importToolSelectionPage;	
	private List<LayoutManagerExtensionElement> layoutManagerExtensionElements;
	private LayoutManagerSelectionPage layoutManagerSelectionPage;
	private OutputFileSelectionPage outputFileSelectionPage;
	private IStructuredSelection selection;
	private boolean 	updateMode= false;
	
	/** 
	 * Orders the items in the target list so that the sort order matches that of the reference list; new items
	 * are placed at the back and sorted by the key generated by the key generator
	 *
	 * @param targetItems the target list that will be reordered 
	 * @param referenceItems the reference list providing the desired order
	 * @param keyProvider the provider of keys allowing item matching
	 */
	private <T extends EObject> void sortTargetList(EList<T> targetItems, EList<T> referenceItems, final IKeyProvider<T> keyProvider) {
		var targetItemsMap = new HashMap<String, T>();
		for (T targetItem : targetItems) {
			var key = keyProvider.getKey(targetItem);
			Assert.isNotNull(key, String.format("missing key (target item): %s",targetItem.toString()));
			Assert.isTrue(!targetItemsMap.containsKey(key), String.format("duplicate key (target item): %s", targetItem.toString()));
			targetItemsMap.put(key, targetItem);
		}
		targetItems.removeAll(new ArrayList<>(targetItems));		

		for (T referenceItem : referenceItems) {
			var key = keyProvider.getKey(referenceItem);
			Assert.isNotNull(key, String.format("missing key (reference item): %s", referenceItem.toString()));
			if (targetItemsMap.containsKey(key)) {
				T targetItem = targetItemsMap.get(key);
				targetItems.add(targetItem);
				targetItemsMap.remove(key);
			}
		}

		var targetLeftoverItems = new ArrayList<T>(targetItemsMap.values());
		Collections.sort(targetLeftoverItems, (item1, item2) -> {	
			var key1 = keyProvider.getKey(item1);
			var key2 = keyProvider.getKey(item2);
			return key1.compareTo(key2);				
		});		
		targetItems.addAll(targetLeftoverItems);
	}

	@Override
	public void addPages() {
		importToolSelectionPage = new ImportToolSelectionPage(importToolExtensionElements, updateMode);		
		addPage(importToolSelectionPage);
		
		// although we don't need the output file selection page when running in update mode, we add it to the
		// wizard because, if we don't, we will not have the opportunity to add the data entry pages for the 
		// selected import tool (including the options page); when in update mode, we will NEVER show the output
		// file selection page however
		outputFileSelectionPage = new OutputFileSelectionPage(selection);
		outputFileSelectionPage.setUpdateMode(updateMode);
		addPage(outputFileSelectionPage);
		
	}
	
	@Override
	public boolean canFinish() {
		if (dataEntryWizardPages == null) {
			// avoid the 'Finish' button to be enabled too soon
			return false;
		} else {
			return super.canFinish();
		}
	}
	
	private void createAndInjectController(final ImportWizardPage wizardPage) {
		// create a controller and inject it in the data entry page's @Controller annotated field
		var controller = 
			new IDataEntryPageController() {
				@Override
				public void setErrorMessage(String message) {
					wizardPage.setErrorMessage(message);
				}
				@Override
				public void setPageComplete(boolean pageComplete) {								
					wizardPage.setPageComplete(pageComplete);
				}						
			};
		wizardPage.getDataEntryPage().setController(controller);
	}
	
	private ImportWizardPage createImportWizardPage(DataEntryPageExtensionElement configElement, boolean firstDataEntryPageInUpdateMode) {
		// create the data entry page
		var dataEntryPage = configElement.createDataEntryPage();		
		
		// wrap the data entry page in a wizard page
		var importWizardPage = new SchemaImportWizardPage(dataEntryPage, configElement.getName(), configElement.getMessage());
		importWizardPage.setFirstDataEntryPageInUpdateMode(firstDataEntryPageInUpdateMode);
		
		dataEntryPage.setContext(context);		
			
		// create a controller and inject it in the data entry page's @Controller annotated field
		createAndInjectController(importWizardPage);
		
		// return the import wizard page
		return importWizardPage;
		
	}

	private void disposeImportTool(SchemaImportToolProxy proxy) {
		if (!proxy.isImportToolDisposed()) {
			proxy.disposeImportTool();
		}
	}
	
	protected void doPostProcessing(Schema targetSchema, Schema referenceSchema) {
		// we'll only do some post-processing when in update mode, allowing the diagram label, if present, to be
		// retained, and to allow for easier validation of the correctness of updating diagrams
		var referenceDiagramLabel = referenceSchema.getDiagramData().getLabel();					
		if (referenceDiagramLabel != null) {
			var targetDiagramLabel = SchemaFactory.eINSTANCE.createDiagramLabel();
			targetSchema.getDiagramData().setLabel(targetDiagramLabel);
			targetDiagramLabel.setWidth(referenceDiagramLabel.getWidth());
			targetDiagramLabel.setHeight(referenceDiagramLabel.getHeight());
			targetDiagramLabel.setDescription(referenceDiagramLabel.getDescription());
			
			var targetDiagramLabelLocation = SchemaFactory.eINSTANCE.createDiagramLocation();
			targetSchema.getDiagramData().getLocations().add(targetDiagramLabelLocation);
			targetDiagramLabel.setDiagramLocation(targetDiagramLabelLocation);
			targetDiagramLabelLocation.setX(referenceDiagramLabel.getDiagramLocation().getX());
			targetDiagramLabelLocation.setY(referenceDiagramLabel.getDiagramLocation().getY());
			targetDiagramLabelLocation.setEyecatcher("diagram label");
		}		
		
		sortTargetList(targetSchema.getDiagramData().getConnectionLabels(), referenceSchema.getDiagramData().getConnectionLabels(), this::getKeyFromConnectionLabel);	
		sortTargetList(targetSchema.getDiagramData().getConnectionParts(), referenceSchema.getDiagramData().getConnectionParts(), this::getKeyFromConnectionPart);		
		sortTargetList(targetSchema.getDiagramData().getConnectors(), referenceSchema.getDiagramData().getConnectors(), this::getKeyFromConnector);
		sortTargetList(targetSchema.getDiagramData().getLocations(), referenceSchema.getDiagramData().getLocations(), DiagramLocation::getEyecatcher);
		sortTargetList(targetSchema.getRecords(), referenceSchema.getRecords(), SchemaRecord::getName);
		sortTargetList(targetSchema.getSets(), referenceSchema.getSets(), Set::getName);
	}
	
	private String getKeyFromConnectionLabel(ConnectionLabel item) {
		if (item.getMemberRole() == null) {
			return null;
   		}
		var set = item.getMemberRole().getSet();
   		if (set == null) {
   			return null;
   		}
   		var memberRecord = item.getMemberRole().getRecord(); 
   		if (memberRecord == null) {
   			return null;
   		}
   		return set.getName() + ":" + memberRecord.getName();
	}
	
	private String getKeyFromConnectionPart(ConnectionPart item) {
		if (item.getMemberRole() == null) {
			return null;
		}
		if (item.getMemberRole().getSet() == null) {
			return null;
		}
		if (item.getMemberRole().getRecord() == null) {
			return null;
		}
		var setName = item.getMemberRole().getSet().getName();
		var recordName = item.getMemberRole().getRecord().getName();
		var i = item.getMemberRole().getConnectionParts().indexOf(item);
		return setName + ":" + recordName + ":" + i;
	}
	
	private String getKeyFromConnector(Connector item) {
		if (item.getConnectionPart() == null) {
			return null;
		}	
		if (item.getConnectionPart().getMemberRole() == null) {
			return null;
		}
		if (item.getConnectionPart().getMemberRole().getSet() == null) {
			return null;
		}
		if (item.getConnectionPart().getMemberRole().getRecord() == null) {
			return null;
		}
		var setName =item.getConnectionPart().getMemberRole().getSet().getName();
		var recordName = item.getConnectionPart().getMemberRole().getRecord().getName();
		int i = item.getConnectionPart()
					.getMemberRole()
					.getConnectionParts()
					.indexOf(item.getConnectionPart());
		return setName + ":" + recordName + ":" + i;
	}

	@Override
	public IWizardPage getNextPage(IWizardPage page) {
		if (page == importToolSelectionPage) {
			return getNextPageForImportToolSelectionPage();
		} else if (page == outputFileSelectionPage) {			
			return getNextPageForOutputFileSelectionPage();
		} else if (dataEntryWizardPages != null && dataEntryWizardPages.contains(page)) {
			return getNextPageForDataEntryWizardPage(page);
		} else {
			return null;
		}
	}
	
	private IWizardPage getNextPageForImportToolSelectionPage() {
		// The user has chosen an import tool and cannot change his/her selection; go get the pre and post data
		// entry pages from the import tool extension element and add all import wizard pages (including the
		// options page which sits in the middle between pre and post options pages); after that we will add the
		// layout manager selection page, which will always be the very last page. Make sure we build and add the
		// wizard pages only once
		
		// step 1: data entry wizard pages
		var importToolExtensionElement = importToolSelectionPage.getExtensionElement();						
		if (dataEntryWizardPages == null) {
			// keep a reference to the active import tool extension element
			activeImportToolExtensionElement = importToolExtensionElement;
			
			// create the list of data entry wizard pages
			dataEntryWizardPages = new ArrayList<>();
			
			// deal with the pre options pages first
			var preOptionsPagesElement = 	activeImportToolExtensionElement.getPreOptionsDataEntryPageExtensionElement();
			var dataEntryPagesElements = 	preOptionsPagesElement.getDataEntryPageExtensionElements();
			for (DataEntryPageExtensionElement dataEntryPageExtensionElement : dataEntryPagesElements) {
				var firstDataEntryPageInUpdateMode = updateMode && dataEntryWizardPages.isEmpty();
				// create a data entry wizard page and add it to our list and to the wizard
				var importWizardPage = createImportWizardPage(dataEntryPageExtensionElement, firstDataEntryPageInUpdateMode);					
				dataEntryWizardPages.add(importWizardPage);
				addPage(importWizardPage);
			}				
			
			// deal with the options wizard page
			var optionsExtensionElement = activeImportToolExtensionElement.getOptionsExtensionElement();
			var optionsWizardPage = new SchemaImportWizardPage(new OptionsPage(optionsExtensionElement), "_optionsPage", "Set options");
			optionsWizardPage.getDataEntryPage().setContext(context);
			createAndInjectController(optionsWizardPage);
			dataEntryWizardPages.add(optionsWizardPage);
			addPage(optionsWizardPage);
							
			// finally, deal with the post options pages (which is also a data entry page)
			var postOptionsPagesElement = activeImportToolExtensionElement.getPostOptionsDataEntryPageExtensionElement();
			dataEntryPagesElements = postOptionsPagesElement.getDataEntryPageExtensionElements();
			for (DataEntryPageExtensionElement dataEntryPageExtensionElement : dataEntryPagesElements) {
				// create a data entry wizard page and add it to our list and to the wizard
				var fimportWizardPage = createImportWizardPage(dataEntryPageExtensionElement, false);					
				dataEntryWizardPages.add(fimportWizardPage);
				addPage(fimportWizardPage);
			}
											
			// step 2: layout manager selection wizard page (import mode only)				
			if (!updateMode) {
				layoutManagerSelectionPage = new LayoutManagerSelectionPage();
				addPage(layoutManagerSelectionPage);
			}
			
		}
		
		if (!updateMode) {
			// import mode: return the output file selection page
			outputFileSelectionPage.setImportToolExtensionElement(importToolExtensionElement);
			return outputFileSelectionPage;
		} else {
			// update mode: return the first import tool data entry page
			dataEntryWizardPages.get(0).aboutToShow();
			return dataEntryWizardPages.get(0);
		}
	}
	
	private IWizardPage getNextPageForOutputFileSelectionPage() {
		// the output file selection page is NEVER shown when in update mode and only added to the wizard for
		// technical reasons
		if (updateMode) {
			throw new IllegalStateException("logic error: the output file selection page should never have been shown when in update mode");
		}
		if (!dataEntryWizardPages.get(0).isRelevant()) {
			var message = String.format("""
					The first page in import contributions must ALWAYS be relevant.
					plug-in: %s
					importTool: %s
					""",
					activeImportToolExtensionElement.getPluginId(), activeImportToolExtensionElement.getName());	
			throw new IllegalStateException(message);
		}
		dataEntryWizardPages.get(0).aboutToShow();
		return dataEntryWizardPages.get(0);
	}
	
	private IWizardPage getNextPageForDataEntryWizardPage(IWizardPage page) {
		int i = dataEntryWizardPages.indexOf(page);
		if (i < 0) {
			throw new IllegalStateException("logic error");
		} else {
			// get the next relevant data entry page, if any
			var nextPage = getNextRelevantPageIndex(i);
			if (nextPage != null) {
				// there is a next relevant data entry page, so return it
				nextPage.aboutToShow();
				return nextPage;
			} else if (!updateMode) {
				// we are in import mode and there is no next relevant data entry page; prepare the layout
				// manager selection page and return it
				var suitableLayoutManagers = new ArrayList<LayoutManagerExtensionElement>();
				for (LayoutManagerExtensionElement extensionElement : layoutManagerExtensionElements) {
					String schemaName = context.getAttribute(IDataEntryContext.SCHEMA_NAME);
					var schemaVersion = ((Short) context.getAttribute(IDataEntryContext.SCHEMA_VERSION)).shortValue();
					if (extensionElement.isValidFor(schemaName, schemaVersion)) {
						suitableLayoutManagers.add(extensionElement);
					}
				}
				layoutManagerSelectionPage.setExtensionElements(suitableLayoutManagers);
				return layoutManagerSelectionPage;
			} else {
				// update mode; there is no next data entry page
				return null;
			}
		}
	}

	private ImportWizardPage getNextRelevantPageIndex(int i) {
		for (int j = i + 1; j < dataEntryWizardPages.size(); j++) {
			if (dataEntryWizardPages.get(j).isRelevant()) {
				return dataEntryWizardPages.get(j);
			}
		}		
		return null;	
	}

	@Override
	public void init(IWorkbench workbench, IStructuredSelection selection) {
		this.selection = selection;
		
		if (updateMode) {
			setWindowTitle("Update");
		} else {
			setWindowTitle("Import");
		}
		
		if (!selection.isEmpty() && selection.getFirstElement() instanceof IFile iFile) {
			fileToUpdate = iFile.getLocation().toFile();			
		}
		
		// build the list of import tool extension elements...
		importToolExtensionElements = ExtensionElementFactory.getExtensionElements(EXTENSION_POINT_IMPORT_ID, 
				ELEMENT_IMPORT_TOOLS, 
				ELEMENT_IMPORT_TOOL, 
				ImportToolExtensionElement.class);
		
		// build the list of layout manager extension elements...
		layoutManagerExtensionElements = ExtensionElementFactory.getExtensionElements(EXTENSION_POINT_IMPORT_ID, 
				ELEMENT_LAYOUT_MANAGERS, 
				ELEMENT_LAYOUT_MANAGER, 
				LayoutManagerExtensionElement.class);		
	}

	@Override
	public boolean performFinish() {
		// get a hold of the import tool and the parameters configured for it in the defining extension
		var importTool = activeImportToolExtensionElement.getSchemaImportTool();
		var importToolParms = activeImportToolExtensionElement.getParameters();	
		
		// store the list of compression routines in the plug-in's preference store
		var contextCompressionProcedures = context.getAttribute(GeneralContextAttributeKeys.COMPRESSION_PROCEDURE_NAMES);
		var store = Plugin.getDefault().getPreferenceStore();
		var q = contextCompressionProcedures.toString();
		store.setValue(PreferenceConstants.COMPRESSION_PROCEDURES, q.substring(1, q.length() - 1));
		
		// create the import tool proxy
		final var proxy = new SchemaImportToolProxy(importTool, context, importToolParms);					
		
		// get a hold of the record layout manager and its (optional) parameters
		LayoutManagerData layoutManagerData;
		if (!updateMode) {
			layoutManagerData = new LayoutManagerData(
					layoutManagerSelectionPage.getExtensionElement().getLayoutManager(),
					layoutManagerSelectionPage.getExtensionElement().getConfiguredParameters(),
					layoutManagerSelectionPage.getUserEnteredParameters());
		} else {
			layoutManagerData = LayoutManagerData.MISSING;
		}
		
		// copy the default diagram data properties to the data entry context (import mode only)
		if (!updateMode) {
			context.setAttribute(IDataEntryContext.DIAGRAMDATA_SHOW_RULERS, store.getBoolean(PreferenceConstants.SHOW_RULERS));
			context.setAttribute(IDataEntryContext.DIAGRAMDATA_SHOW_GRID, store.getBoolean(PreferenceConstants.SHOW_GRID));
			context.setAttribute(IDataEntryContext.DIAGRAMDATA_SNAP_TO_GUIDES, store.getBoolean(PreferenceConstants.SNAP_TO_GUIDES));
			context.setAttribute(IDataEntryContext.DIAGRAMDATA_SNAP_TO_GRID, store.getBoolean(PreferenceConstants.SNAP_TO_GRID));
			context.setAttribute(IDataEntryContext.DIAGRAMDATA_SNAP_TO_GEOMETRY, store.getBoolean(PreferenceConstants.SNAP_TO_GEOMETRY));
		}
		
		// populate the schema and persist it to the file specified by the user - do the work within an operation
		File targetFile;
		if (!updateMode) {
			targetFile = outputFileSelectionPage.getOutputFile();
		} else {
			targetFile = fileToUpdate;			
		}
		var errorMessage = createSchema(proxy, layoutManagerData, targetFile);
		if (errorMessage != null) {
			MessageDialog.openError(PlatformUI.getWorkbench().getActiveWorkbenchWindow().getShell(), "File Creation", errorMessage);
			return false;
		}
		
		// refresh the resource in the workspace to avoid 'Resource is out of sync with the file system' messages
		var fullPath = new Path(targetFile.getAbsolutePath());
		var workspacePath = ResourcesPlugin.getWorkspace().getRoot().getLocation();
		var path = new Path(fullPath.toString().substring(workspacePath.toString().length()));
		var modelFile = ResourcesPlugin.getWorkspace().getRoot().getFile(path);	
		try {
			modelFile.getProject().refreshLocal(IResource.DEPTH_INFINITE, null);
		} catch (CoreException | OperationCanceledException e) {
			logger.error("Error while refreshing workspace", e);
		}
		
		// select the new file resource in the current view
		var activePart = PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage().getActivePart();
		if (activePart instanceof ISetSelectionTarget setSelectionTarget) {
			setSelectionTarget.selectReveal(new StructuredSelection(modelFile));
		}
		// open an editor on the new file (this will only work if the file extension is .schema)
		try {
			PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage().openEditor(new FileEditorInput(modelFile), 
					PlatformUI.getWorkbench().getEditorRegistry().getDefaultEditor(modelFile.getFullPath().toString()).getId());	
		} catch (PartInitException exception) {
			logger.error("Error while opening imported schema", exception);			
			MessageDialog.openError(PlatformUI.getWorkbench().getActiveWorkbenchWindow().getShell(), "Open Editor", exception.getMessage());
			return false;
		}
		
		// signal the success of the wizard operation...
		return true;
	}
	
	private String createSchema(SchemaImportToolProxy proxy, LayoutManagerData layoutManagerData, File targetFile) {
		try {
			org.lh.dmlj.schema.editor.Plugin.getDefault().runWithOperationInProgressIndicator(createIRunnableWithProgress(proxy, layoutManagerData, targetFile));
			return null;
		} catch (Exception e) {
			// the plug-in's runWithOperationInProgressIndicator method has already logged the error
			var unknownErrorMessage = "Unknown error while importing schema";
			var messagePrefix = "Error while importing schema: %s";
			if (e.getCause() instanceof InvocationTargetException ite) {
				if (ite.getMessage() != null) {
					return String.format(messagePrefix, ite.getMessage());
				} else if (ite.getTargetException() != null && ite.getTargetException().getMessage() != null) {
					return String.format(messagePrefix, ite.getTargetException().getMessage());
				} else {
					return unknownErrorMessage;
				}
			} else if (e.getCause() != null && e.getCause().getMessage() != null) {
				return String.format(messagePrefix, e.getCause().getMessage());
			} else if (e.getMessage() != null) {
				return String.format(messagePrefix, e.getMessage());
			} else {
				return unknownErrorMessage;
			}
		}
	}
	
	private IRunnableWithProgress createIRunnableWithProgress(SchemaImportToolProxy proxy, LayoutManagerData layoutManagerData, File targetFile) {
		return progressMonitor -> {
			progressMonitor.beginTask(updateMode ? "Update Schema" : "Import Schema", 100);
			try {
				// create the schema and perform validations as we go
				var schema = proxy.invokeImportTool(progressMonitor);					
				
				// create a layout manager and invoke its layout() method to set the diagram location for all
				// records, system owners and set labels - perform validations as we go					
				ILayoutManager layoutManager;
				if (!updateMode) {
					// import mode: use the layout manager selected by the user
					layoutManager = new ImportLayoutManager(schema, layoutManagerData.recordLayoutManager(),
							layoutManagerData.configuredLayoutManagerParms(), layoutManagerData.userSpecifiedLayoutManagerParms());
				} else {
					// update mode: use a dedicated layout manager that will reuse as much as possible from the
					// schema contained in the file referred to by the current selection
					layoutManager = new UpdateLayoutManager(schema, fileToUpdate);						
				}
				layoutManager.layout();					
				
				// perform post-processing
				if (updateMode) {
					doPostProcessing(schema, layoutManager.getReferenceSchema());
				}
				
				Tools.writeToFile(schema, targetFile);
			} catch (Exception exception) {
				tryToDeleteFileCreated(outputFileSelectionPage.getOutputFile());
				throw new IllegalStateException(exception);
			} finally {
				disposeImportTool(proxy);
			}
			progressMonitor.done();
		};
	}
	
	private void tryToDeleteFileCreated(File fileCreated) {
		if (fileCreated.exists()) {
			try {
				Files.delete(fileCreated.toPath());
			} catch (IOException e) {
				var message = String.format("could not delete file %s after a failed CA IDMS/DB schema import", fileCreated.getAbsolutePath());
				logger.warning(message);
			}
		}
	}

	public void setUpdateMode(boolean newValue) {
		updateMode = newValue;		
	}
	
	private static interface IKeyProvider<T> {
		String getKey(T item);
	}
	
	public static record LayoutManagerData(
			AbstractRecordLayoutManager recordLayoutManager,
			Properties configuredLayoutManagerParms,
			Properties userSpecifiedLayoutManagerParms) {
		
		public static final LayoutManagerData MISSING = new LayoutManagerData(null, null, null);
	}
	
}
